# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# To get proper caching for monorepos we use actions/cache@eb78578266b7cec649ab65b6f1534bd6040c838b (from master branch) 
# instead of actions/cache@1. Support for monorepos will be available in actions/cache@2.

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: restore lerna
        id: cache
        uses: actions/cache@eb78578266b7cec649ab65b6f1534bd6040c838b
        with:
          path: |
            node_modules
            */*/node_modules
          key: n-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      # - name: Build local packages
      #   run: yarn build
      - run: yarn test
        env:
          CI: true
